import pandas as pd

from forecast_config import SYSTEM_STATUS_PATH
from metrics import weighted_summary
from time_utils import to_utc_naive


def format_float(value, digits=2, suffix=""):
    if value is None or pd.isna(value):
        return "n/a"
    return f"{float(value):.{digits}f}{suffix}"


def markdown_table(rows, headers):
    if not rows:
        return "_No rows._"

    table = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join(["---"] * len(headers)) + " |",
    ]
    for row in rows:
        table.append("| " + " | ".join(str(row.get(header, "")) for header in headers) + " |")
    return "\n".join(table)


def build_target_metric_rows(metrics):
    rows = []
    if metrics.empty:
        return rows

    for target_key, group in metrics.groupby("target"):
        summary = weighted_summary(group)
        rows.append({
            "target": target_key,
            "samples": summary["samples"],
            "forecast_mae_c": format_float(summary["forecast_mae_c"], 2),
            "raw_mae_c": format_float(summary["raw_mae_c"], 2),
            "persistence_mae_c": format_float(summary["persistence_mae_c"], 2),
            "vs_raw_c": format_float(summary["mae_improvement_vs_raw_c"], 2),
            "vs_persistence_c": format_float(summary["mae_improvement_vs_persistence_c"], 2),
            "coverage": format_float(summary["coverage_rate"] * 100, 1, "%"),
            "leads_better_raw": f"{summary['leads_better_than_raw']}/{len(group)}",
        })
    return rows


def build_problem_lead_rows(metrics):
    if metrics.empty:
        return []

    problem_leads = metrics[
        (metrics["mae_improvement_vs_raw_c"] < 0)
        | (metrics["mae_improvement_vs_persistence_c"] < 0)
        | (metrics["coverage_rate"] < 0.70)
    ].copy()
    if problem_leads.empty:
        return []

    problem_leads["sort_risk"] = problem_leads[[
        "mae_improvement_vs_raw_c",
        "mae_improvement_vs_persistence_c",
    ]].min(axis=1)
    problem_leads = problem_leads.sort_values(["sort_risk", "coverage_rate"]).head(12)
    rows = []
    for _, row in problem_leads.iterrows():
        rows.append({
            "target": row["target"],
            "lead_hour": int(row["lead_hour"]),
            "samples": int(row["sample_count"]),
            "forecast_mae_c": format_float(row["forecast_mae_c"], 2),
            "raw_mae_c": format_float(row["raw_mae_c"], 2),
            "persistence_mae_c": format_float(row["persistence_mae_c"], 2),
            "vs_raw_c": format_float(row["mae_improvement_vs_raw_c"], 2),
            "vs_persistence_c": format_float(row["mae_improvement_vs_persistence_c"], 2),
            "coverage": format_float(row["coverage_rate"] * 100, 1, "%"),
        })
    return rows


def build_system_status(
    run_time,
    latest_observation_time,
    forecast_archive,
    verification,
    metrics,
    ecmwf_source,
    self_test_status,
):
    summary = weighted_summary(metrics)
    target_rows = build_target_metric_rows(metrics)
    problem_rows = build_problem_lead_rows(metrics)

    if forecast_archive.empty:
        archive_window = "n/a"
    else:
        archive_run_times = pd.to_datetime(forecast_archive["run_time"], errors="coerce")
        archive_window = f"{archive_run_times.min()} to {archive_run_times.max()} UTC"

    if verification.empty:
        verification_window = "n/a"
    else:
        verification_times = pd.to_datetime(verification["valid_time"], errors="coerce")
        verification_window = f"{verification_times.min()} to {verification_times.max()} UTC"

    run_time_text = to_utc_naive(run_time)
    latest_obs_text = to_utc_naive(latest_observation_time)
    status = "green" if summary["samples"] and summary["mae_improvement_vs_raw_c"] > 0 else "warming up"

    lines = [
        "# Forecast System Status",
        "",
        "This file is regenerated by the hourly forecast workflow.",
        "",
        "## Current Status",
        "",
        f"- Status: `{status}`",
        f"- Last successful run time: `{run_time_text} UTC`",
        f"- Latest observation used: `{latest_obs_text} UTC`",
        f"- ECMWF source used: `{ecmwf_source or 'unknown'}`",
        f"- Self-test: `{self_test_status}`",
        f"- Archive rows: `{len(forecast_archive)}`",
        f"- Verified forecast rows: `{len(verification)}`",
        f"- Metric rows: `{len(metrics)}`",
        f"- Archive run window: `{archive_window}`",
        f"- Verification valid-time window: `{verification_window}`",
        "",
        "## Overall Metrics",
        "",
        markdown_table(
            [{
                "samples": summary["samples"],
                "forecast_mae_c": format_float(summary["forecast_mae_c"], 2),
                "raw_mae_c": format_float(summary["raw_mae_c"], 2),
                "persistence_mae_c": format_float(summary["persistence_mae_c"], 2),
                "vs_raw_c": format_float(summary["mae_improvement_vs_raw_c"], 2),
                "vs_persistence_c": format_float(summary["mae_improvement_vs_persistence_c"], 2),
                "coverage": format_float(summary["coverage_rate"] * 100, 1, "%"),
                "leads_better_raw": f"{summary['leads_better_than_raw']}/{summary['rows']}",
                "leads_better_persistence": (
                    f"{summary['leads_better_than_persistence']}/{summary['rows']}"
                ),
            }],
            [
                "samples",
                "forecast_mae_c",
                "raw_mae_c",
                "persistence_mae_c",
                "vs_raw_c",
                "vs_persistence_c",
                "coverage",
                "leads_better_raw",
                "leads_better_persistence",
            ],
        ),
        "",
        "Positive `vs_raw_c` and `vs_persistence_c` means the corrected forecast is better.",
        "",
        "## Metrics By Target",
        "",
        markdown_table(
            target_rows,
            [
                "target",
                "samples",
                "forecast_mae_c",
                "raw_mae_c",
                "persistence_mae_c",
                "vs_raw_c",
                "vs_persistence_c",
                "coverage",
                "leads_better_raw",
            ],
        ),
        "",
        "## Lead Hours To Watch",
        "",
        markdown_table(
            problem_rows,
            [
                "target",
                "lead_hour",
                "samples",
                "forecast_mae_c",
                "raw_mae_c",
                "persistence_mae_c",
                "vs_raw_c",
                "vs_persistence_c",
                "coverage",
            ],
        ),
        "",
        "## Plots And Raw Files",
        "",
        "- Forecast page: [forecast_Inaquito.html](forecast_Inaquito.html)",
        "- Metrics dashboard: [forecast_metrics.html](forecast_metrics.html)",
        "- Current forecast CSV: [forecast_output.csv](forecast_output.csv)",
        "- Forecast archive: [forecast_archive.csv](forecast_archive.csv)",
        "- Forecast verification: [forecast_verification.csv](forecast_verification.csv)",
        "- Forecast metrics: [forecast_metrics.csv](forecast_metrics.csv)",
        "",
        "## Operational Notes",
        "",
        "- The workflow should stay green even when one ECMWF mirror rate-limits; it tries Azure, Google, then AWS.",
        "- A red workflow should be classified as data-source outage, ECMWF mirror outage, dependency issue, Python exception, or git push conflict before changing model logic.",
        "- Do not add a more complex model unless this report shows the current correction beats raw ECMWF and persistence over enough samples.",
        "",
    ]
    SYSTEM_STATUS_PATH.write_text("\n".join(lines), encoding="utf-8")
