name: Forecast Automation

on:
  schedule:
    - cron: '0 * * * *'  # This cron expression schedules the job to run every hour

jobs:
  run-forecast:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install ecmwflibs eccodes cfgrib ecmwf-opendata
        pip install pandas requests numpy matplotlib scikit-learn tensorflow statsmodels plotly xarray

    - name: Run Forecast Script
      run: python script.py  # Replace with the actual name of your script

    - name: Configure Git
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"

    - name: Pull Latest Changes
      run: git pull origin master  # Replace 'master' with 'main' if your default branch is named 'main'

    - name: Commit and Push Results
      run: |
        git add merged_data_export.csv
        git commit -m "Updated forecast data"
        git push origin master  # Replace 'master' with 'main' if your default branch is named 'main'
      env:
        GITHUB_TOKEN: ${{ secrets.WEATHER_FORECAST }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.WEATHER_FORECAST }}
        publish_dir: ./  # This will publish the root directory to GitHub Pages
