name: Forecast Automation

on:
  schedule:
    - cron: '0 * * * *'  # Runs the job every hour

jobs:
  run-forecast:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies in Virtual Environment
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install pandas 

    - name: Run Forecast Script
      
      run: |
        source venv/bin/activate
        python script.py

    - name: Configure Git
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"

    - name: Pull Latest Changes and Merge
      run: |
        git fetch origin
        git merge origin/master  # Merges remote changes into local branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit and Push Results
      run: |
        git add merged_data_export.csv
        git commit -m "Updated forecast data"
        git push origin master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Publishes the root directory to GitHub Pages